Package.describe({
    name: "trepafi:semantic-ui",
    summary: "Semantic UI for Meteor",
    version: "0.1.0",
    git: "https://github.com/trepafi/meteor-semantic-ui.git"
});


Package.onUse(function (api) {
    api.versionsFrom('1.0');
    api.use(['jquery'], ['client']);
    api.addFiles(getFiles(), ['client']);

    function getFiles() {
        return [
            'src/components/accordion.css',
            'src/components/accordion.jss',
            'src/components/api.js',
            'src/components/breadcrumb.css',
            'src/components/button.css',
            'src/components/card.css',
            'src/components/checkbox.css',
            'src/components/checkbox.js',
            'src/components/colorize.js',
            'src/components/comment.css',
            'src/components/dimmer.css',
            'src/components/dimmer.js',
            'src/components/divider.css',
            'src/components/dropdown.css',
            'src/components/dropdown.js',
            'src/components/feed.css',
            'src/components/flag.css',
            'src/components/form.css',
            'src/components/form.js',
            'src/components/grid.css',
            'src/components/header.css',
            'src/components/icon.css',
            'src/components/image.css',
            'src/components/input.css',
            'src/components/item.css',
            'src/components/label.css',
            'src/components/list.css',
            'src/components/loader.css',
            'src/components/menu.css',
            'src/components/message.css',
            'src/components/modal.css',
            'src/components/modal.js',
            'src/components/nag.css',
            'src/components/nag.js',
            'src/components/popup.css',
            'src/components/popup.js',
            'src/components/progress.css',
            'src/components/progress.js',
            'src/components/rail.css',
            'src/components/rating.css',
            'src/components/rating.js',
            'src/components/reset.css',
            'src/components/reveal.css',
            'src/components/search.css',
            'src/components/search.js',
            'src/components/segment.css',
            'src/components/shape.css',
            'src/components/shape.js',
            'src/components/sidebar.css',
            'src/components/sidebar.js',
            'src/components/site.css',
            'src/components/site.js',
            'src/components/state.js',
            'src/components/statistic.css',
            'src/components/step.css',
            'src/components/sticky.css',
            'src/components/sticky.js',
            'src/components/tab.css',
            'src/components/tab.js',
            'src/components/table.css',
            'src/components/transition.css',
            'src/components/transition.js',
            'src/components/video.css',
            'src/components/video.js',
            'src/components/visibility.js',
            'src/components/visit.js',
            'src/themes/basic/assets/fonts/icons.eot',
            'src/themes/basic/assets/fonts/icons.svg',
            'src/themes/basic/assets/fonts/icons.ttf',
            'src/themes/basic/assets/fonts/icons.woff',
            'src/themes/default/assets/fonts/icons.eot',
            'src/themes/default/assets/fonts/icons.eotf',
            'src/themes/default/assets/fonts/icons.svg',
            'src/themes/default/assets/fonts/icons.ttf',
            'src/themes/default/assets/fonts/icons.woff',
            'src/themes/default/assets/images/flags.png',
            'src/semantic.css',
            'src/semantic.js'
        ];
    }

});