Package.describe({
    name: "trepafi:semantic-ui",
    summary: "Semantic UI for Meteor",
    version: "0.1.1",
    git: "https://github.com/trepafi/meteor-semantic-ui.git"
});


Package.onUse(function (api) {
    api.versionsFrom('1.0');
    api.use(['jquery'], ['client']);
    api.addFiles(getFiles(), ['client']);

    function getFiles() {
        return [
            'src/components/accordion.min.css',
            'src/components/accordion.min.js',
            'src/components/ad.min.css',
            'src/components/api.min.js',
            'src/components/breadcrumb.min.css',
            'src/components/button.min.css',
            'src/components/card.min.css',
            'src/components/checkbox.min.css',
            'src/components/checkbox.min.js',
            'src/components/comment.min.css',
            'src/components/dimmer.min.css',
            'src/components/dimmer.min.js',
            'src/components/divider.min.css',
            'src/components/dropdown.min.css',
            'src/components/dropdown.min.js',
            'src/components/feed.min.css',
            'src/components/flag.min.css',
            'src/components/form.min.css',
            'src/components/form.min.js',
            'src/components/grid.min.css',
            'src/components/header.min.css',
            'src/components/icon.min.css',
            'src/components/image.min.css',
            'src/components/input.min.css',
            'src/components/item.min.css',
            'src/components/label.min.css',
            'src/components/list.min.css',
            'src/components/loader.min.css',
            'src/components/menu.min.css',
            'src/components/message.min.css',
            'src/components/modal.min.css',
            'src/components/modal.min.js',
            'src/components/nag.min.css',
            'src/components/nag.min.js',
            'src/components/popup.min.css',
            'src/components/popup.min.js',
            'src/components/progress.min.css',
            'src/components/progress.min.js',
            'src/components/rail.min.css',
            'src/components/rating.min.css',
            'src/components/rating.min.js',
            'src/components/reset.min.css',
            'src/components/reveal.min.css',
            'src/components/search.min.css',
            'src/components/search.min.js',
            'src/components/segment.min.css',
            'src/components/shape.min.css',
            'src/components/shape.min.js',
            'src/components/sidebar.min.css',
            'src/components/sidebar.min.js',
            'src/components/site.min.css',
            'src/components/site.min.js',
            'src/components/state.min.js',
            'src/components/statistic.min.css',
            'src/components/step.min.css',
            'src/components/sticky.min.css',
            'src/components/sticky.min.js',
            'src/components/tab.min.css',
            'src/components/tab.min.js',
            'src/components/table.min.css',
            'src/components/transition.min.css',
            'src/components/transition.min.js',
            'src/components/video.min.css',
            'src/components/video.min.js',
            'src/components/visibility.min.js',
            'src/themes/basic/assets/fonts/icons.eot',
            'src/themes/basic/assets/fonts/icons.svg',
            'src/themes/basic/assets/fonts/icons.ttf',
            'src/themes/basic/assets/fonts/icons.woff',
            'src/themes/default/assets/fonts/icons.eot',
            'src/themes/default/assets/fonts/icons.otf',
            'src/themes/default/assets/fonts/icons.svg',
            'src/themes/default/assets/fonts/icons.ttf',
            'src/themes/default/assets/fonts/icons.woff',
            'src/themes/default/assets/images/flags.png',
            'src/semantic.min.css',
            'src/semantic.min.js'
        ];
    }

});
